version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    command: --max_allowed_packet=32505856
    container_name: jf-mariadb
    hostname: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: julianneFurnishings
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pmariadb",
        ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s

  julianne-furnishings:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: julianne-furnishings
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    ports:
      - "5000:5000"
      - "9229:9229"
    restart: always
    volumes:
      - ./:/app
