version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: jf-mariadb-test
    hostname: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: julianneFurnishingsTest
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    restart: unless-stopped

  julianne-furnishings:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: julianne-furnishings-test
    depends_on:
      mariadb:
        condition: service_started
        restart: true
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ./:/app
