# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      SERVER_PORT: 5000
      LOG_LEVEL: "debug"
      LOG_LOCATION: "./test.log"
      CORS_ORIGIN: 127.0.0.1
      DATABASE_NAME: "test"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DATABASE_DIALECT: "mysql"

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Initialize MySQL
        run: sudo systemctl start mysql.service

      - name: Initialize database
        run: |
          mysql -h ${{ env.DATABASE_HOST }} -e 'CREATE DATABASE ${{ env.DATABASE_NAME }};' -u ${{ env.DATABASE_USER }} -p ${{ env.DATABASE_PASSWORD }}

      - name: Boost database user
        run: |
          mysql -h ${{ env.DATABASE_HOST }} -e "ALTER USER '${{ env.DATABASE_USER }}'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';" -u ${{ env.DATABASE_USER }} -p ${{ env.DATABASE_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Verify MySQL connection
        env:
          PORT: 3306
        run: |
          while ! mysqladmin ping -h "127.0.0.1" -P "${{ env.DATABASE_PORT }}" --silent; do
            sleep 1
          done

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci
